### ISSUE TITLE
build fails with auth problem on PKS-GCP when building against GCR

### ISSUE THREAD

**Issue by trisberg** [buildpack/knative-integration#2]
I have a PKS v1.3 cluster where a simple cnb build fails due to some auth issue with GCR.

Building this:

```
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: cnb-example-build
spec:
  serviceAccountName: riff-build
  source:
    git:
      url: https://github.com/trisberg/hello-knative.git
      revision: master
  template:
    name: buildpacks-cnb
    arguments:
    - name: IMAGE
      value: us.gcr.io/cf-sandbox-trisberg/hello-knative-pks
```

I end up with this error:

```
{"level":"warn","ts":1555075935.036583,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/upstream/release-0.5\" is not a valid GitHub commit ID"}
{"level":"info","ts":1555075935.039349,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
{"level":"warn","ts":1555075936.70994,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/upstream/release-0.5\" is not a valid GitHub commit ID"}
{"level":"info","ts":1555075937.1317787,"logger":"fallback-logger","caller":"git-init/main.go:101","msg":"Successfully cloned \"https://github.com/trisberg/hello-knative.git\" @ \"master\" in path \"/workspace\""}
2019/04/12 13:32:29 Trying group of 1...
2019/04/12 13:32:29 ======== Results ========
2019/04/12 13:32:29 Sample Node.js Buildpack: fail
2019/04/12 13:32:29 Trying group of 1...
2019/04/12 13:32:29 ======== Results ========
2019/04/12 13:32:29 Sample Java Buildpack: pass
2019/04/12 13:32:30 Error: failed to : DENIED: Permission denied for "latest" from request "/v2/cf-sandbox-trisberg/hello-knative-pks/manifests/latest". 
```

The `riff-build` service account has the right creds specified AFAICT:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-04-12T03:13:29Z"
  labels:
    projectriff.io/installer: riff
    projectriff.io/version: 0.3.0
  name: riff-build
  namespace: default
  resourceVersion: "8911"
  selfLink: /api/v1/namespaces/default/serviceaccounts/riff-build
  uid: f1dd1226-5cd0-11e9-a683-42010a000b0a
secrets:
- name: push-credentials
- name: riff-build-token-bsjqp
```

The `push-credentials` (key redacted):
```
apiVersion: v1
data:
  password: ewogICJ0eXBlIjogInNlcnZ...hbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
  username: X2pzb25fa2V5
kind: Secret
metadata:
  annotations:
    build.knative.dev/docker-0: https://gcr.io
  creationTimestamp: "2019-04-12T03:13:29Z"
  labels:
    projectriff.io/installer: riff
    projectriff.io/version: 0.3.0
  name: push-credentials
  namespace: default
  resourceVersion: "8908"
  selfLink: /api/v1/namespaces/default/secrets/push-credentials
  uid: f1ccb2c9-5cd0-11e9-a683-42010a000b0a
type: kubernetes.io/basic-auth
```

**Comment by trisberg** [comment]
Knative version is v0.5.0 + istio v1.0.7 and build version is also v0.5.0

**Comment by ekcasey** [comment]
@trisberg I assume you aren't using the vanilla `cnb` build-template https://github.com/knative/build-templates/blob/master/buildpacks/cnb.yaml? That template doesn't currently provide a way to inject registry credentials using k8s secrets (It assumes you can use the IAAS specific `docker-credential-helpers` to get the job done, which will work on GKE or similar, but not PKS). I would need to know more about the build-template to help debug.

We do hope to build out tooling in this repo to support similar workflows.

@matthewmcnew might also be able to provide some help here. I know he has been working on getting a `knative` template running on PKS as well.

**Comment by trisberg** [comment]
Thanks @ekcasey, I was using the vanilla cnb build-template, and also the [riff build-template](https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate-0.2.0.yaml)

This is an area where we do need to gain some understanding of limitations and roadmap since we do need this for riff/PFS on PKS. Seems that what we had for the riff v0.2.0 release a few months ago worked fine.

**Comment by matthewmcnew** [comment]
It looks like our credhelpers are overwriting the credentials provided from your service account. Could you update your build to include the USE_CRED_HELPERS=false argument?

```
 arguments:
    - name: USE_CRED_HELPERS
      value: 'false'
```

Also, we don't yet properly associate us.gcr.io with the gcr.io secret you provided. Could you update the image to not include the 'us' before the gcr format?

```
 arguments:
    - name: IMAGE
      value: gcr.io/cf-sandbox-trisberg/hello-knative-pks
```

**Comment by matthewmcnew** [comment]
Alternatively, you could annotate your secret with:
```
 annotations:
    build.knative.dev/docker-0: https://gcr.io
    build.knative.dev/docker-1: https://us.gcr.io
```

**Comment by trisberg** [comment]
We don't typically use the `us.gcr.io` prefix, that snuck in there since I copied the [example[(https://github.com/knative/build-templates/tree/master/buildpacks#usage) from the build-template repo for buildpacks and then modified it for my use

**Comment by trisberg** [comment]
So, turning off USE_CRED_HELPERS seems to work. Should we always use that or only in certain environments?

**Comment by matthewmcnew** [comment]
You should use USE_CRED_HELPERS=false whenever you use a secret via a service account. 

We typically just make that the default in our cnb-build template when running on PKS.

**Comment by trisberg** [comment]
Thanks for your help, closing this now.
